
omod EVENT-QUEUE is
  protecting CONST-TAGGED-EVENTS .
  including ABS-EVENT-QUEUE .

  var EVENTS : Events .
  var TAG : Tag .
  var QUEUE : EQueue .

  --- in the symbolic setting, an event queue is a set, because
  --- the order cannot be fully determined with symbolic times
  op _;;_ : EQueue EQueue -> EQueue [ctor comm assoc id: empty] .

  --- this function just adds a tagged event to the set
  eq insert(EVENTS at TAG, QUEUE) = (EVENTS at TAG) ;; QUEUE . 
endom

