
omod EXECUTE-REACTION is
  including ABS-EXECUTE-REACTION .

  var REACTOR : ReactorId .
  var TSTATUS : TriggerStatus .
  vars RB RB1 RB2 : ReactionBody .
  var OUTPUTS : Events .
  var QUEUE : EQueue .
  var VALUATION : ReactorState .
  vars ACTIONS INPORTS : Configuration .
  var BEXP : BoolExpr .
  var CONST : BoolValue .
  vars LT PT : Time .

  --- the semantics of if-then-else-fi for the concrete case
  eq executeReactionBody(
        < REACTOR : Reactor | state :  VALUATION,
                              inports : INPORTS, actions : ACTIONS >,
        (if BEXP then RB1 else RB2 fi) ; RB, OUTPUTS, QUEUE, TSTATUS, CONST, LT, PT)
   =                                         
      executeReactionBody(< REACTOR : Reactor | >,
        if eval(BEXP, VALUATION, INPORTS ACTIONS, TSTATUS) == trueVal 
        then (RB1 ; RB) else (RB2 ; RB) fi,  
        OUTPUTS, QUEUE, TSTATUS, CONST, LT, PT) .
endom


omod EXECUTE-STEP is
  including EXECUTE-REACTION .
  including ABS-EXECUTE-STEP .
  including INVOKED .
  including LF-TIMELINES .

  vars REACTORID : ReactorId .
  vars PRE INVOKED : ReactionIdSet .
  vars OS TRIGGERIDS : OidSet .
  vars NETWORK GRAPH : Configuration .
  var OBJECT : Object .
  var TSTATUS : TriggerStatus .
  vars REACTIONS1 REACTIONS2 : ReactionList .
  var OUTPUTS : Events .
  vars QUEUE RESULT-QUEUE : EQueue .
  vars RB RB2 : ReactionBody .
  vars CONST CONST' : BoolValue .
  vars N N2 NP : Nat .
  vars T T1 LT PT : Time .
  vars TI TI1 : TimeInf .
  vars RXNS Q : Oid .

  --- This starts an execution of an enabled reaction. Notice: we perform all the statements in the reaction body already at the beginning
  --- of the execution and we update the event queue and the ports accordingly. However, this should not impact the logic of the system
  --- since other reactions that read these values will not be enabled until the status of this reaction is executed.
  crl [startExecuteReaction] :
    executeStep(
            < (REACTORID . N) : APGNode | 
                triggers : TSTATUS, status : present, pre : PRE > 
            GRAPH,
            LT,
            NETWORK
            < REACTORID : Reactor | 
                reactions : REACTIONS1 (reaction N when TRIGGERIDS --> OS do {RB} deadline TI {RB2} exTime T1 TI1 ) REACTIONS2 >
          < Q : EventQueue | queue : QUEUE >
          ([physicalTime: PT])
          [numberProcessors: s NP]
          < RXNS : Invoked | reactions : INVOKED >, 
            CONST
          )
    =>
      executeStep(
        < (REACTORID . N) : APGNode | status : executing(zero) >
        updateGraph(GRAPH, REACTORID, OS, NETWORK < REACTORID : Reactor | >, OUTPUTS),
        LT,
        propagateImmediateOutputs(OUTPUTS, NETWORK OBJECT)    --- updated reactor
        < Q : EventQueue | queue : scheduleDelayedInputs(OUTPUTS, NETWORK, RESULT-QUEUE, LT) >
        [physicalTime: PT] 
        [numberProcessors: NP]
        < RXNS : Invoked | reactions : INVOKED ; (REACTORID . N) >,
        CONST && CONST'
      )
    if presetOK(PRE, GRAPH)   
    /\ allTriggersDecided(TSTATUS)  
    /\ result(OBJECT, OUTPUTS, RESULT-QUEUE, CONST') := 
         executeReaction(< REACTORID : Reactor | reactions : REACTIONS1
                                                 (reaction N when TRIGGERIDS --> OS do {RB} deadline TI {RB2} exTime T1 TI1)
                                                 REACTIONS2 >, N, TSTATUS, QUEUE, LT, PT) .

--- Execution finished. We update the APG execution status accordingly and we free one processor.
crl [finishExecuteReaction] :
  executeStep(
            < (REACTORID . N) : APGNode | status : executing(T) > 
            GRAPH,
            LT,
            NETWORK
            < REACTORID : Reactor | 
                reactions : REACTIONS1 (reaction N when TRIGGERIDS --> OS do {RB} deadline TI {RB2} exTime T1 TI1 ) REACTIONS2 >
            [numberProcessors: NP],
            CONST
            )
  =>
  executeStep(
            < (REACTORID . N) : APGNode | status : executed > 
            GRAPH,
            LT,
            NETWORK
            < REACTORID : Reactor | >
            [numberProcessors: s NP],
            CONST
            )
  if T ge T1 /\ T le TI1 .

  ceq executeStep(
            GRAPH,
            LT,
            NETWORK,
            CONST
        )
  =
       finished(NETWORK)
       if allFinished(GRAPH) .

op finished : Configuration -> Configuration [ctor frozen] .

endom
