
omod EXECUTE-REACTION is
  including ABS-EXECUTE-REACTION .

  var REACTOR : ReactorId .
  var TSTATUS : TriggerStatus .
  vars RB RB1 RB2 : ReactionBody .
  var OUTPUTS : Events .
  var QUEUE : EQueue .
  var VALUATION : ReactorState .
  vars ACTIONS INPORTS : Configuration .
  var BEXP : BoolExpr .
  var CONST : BoolValue .
  vars LT PT : Time .

  --- the semantics of if-then-else-fi for the concrete case
  eq executeReactionBody(
        < REACTOR : Reactor | state :  VALUATION,
                              inports : INPORTS, actions : ACTIONS >,
        (if BEXP then RB1 else RB2 fi) ; RB, OUTPUTS, QUEUE, TSTATUS, CONST, LT, PT)
   =                                         
      executeReactionBody(< REACTOR : Reactor | >,
        if eval(BEXP, VALUATION, INPORTS ACTIONS, TSTATUS) == trueVal 
        then (RB1 ; RB) else (RB2 ; RB) fi,  
        OUTPUTS, QUEUE, TSTATUS, CONST, LT, PT) .
endom


omod EXECUTE-STEP is
  including EXECUTE-REACTION .
  including ABS-EXECUTE-STEP .

  vars REACTORID : ReactorId .
  vars PRE INVOKED : ReactionIdSet .
  vars OS TRIGGERIDS : OidSet .
  vars NETWORK GRAPH : Configuration .
  var OBJECT : Object .
  var TSTATUS : TriggerStatus .
  vars REACTIONS1 REACTIONS2 : ReactionList .
  var OUTPUTS : Events .
  vars QUEUE RESULT-QUEUE : EQueue .
  vars RB RB2 : ReactionBody .
  vars CONST CONST' : BoolValue .
  vars N N2 : Nat .
  vars T T1 LT PT : Time .
  vars TI TI1 : TimeInf .

  --- This starts an execution of an enabled reaction. Notice: we perform all the statements in the reaction body already at the beginning
  --- of the execution and we update the event queue and the ports accordingly. However, this should not impact the logic of the system
  --- since other reactions that read these values will not be enabled until the status of this reaction is executed.
  crl [startExecuteReaction] :
    executeStep(
            < (REACTORID . N) : APGNode | 
                triggers : TSTATUS, status : present, pre : PRE > 
            GRAPH,
            NETWORK
            < REACTORID : Reactor | 
                reactions : REACTIONS1 (reaction N when TRIGGERIDS --> OS do {RB} deadline TI {RB2} exTime T1 TI1 ) REACTIONS2 >,
            QUEUE,
            INVOKED, CONST, LT, PT, s N2  --- last argument is the number of idle processors
            )
    =>
      executeStep(
        < (REACTORID . N) : APGNode | status : executing(zero) >
        updateGraph(GRAPH, REACTORID, OS, NETWORK < REACTORID : Reactor | >, OUTPUTS),
        propagateImmediateOutputs(OUTPUTS, NETWORK OBJECT),    --- updated reactor
        scheduleDelayedInputs(OUTPUTS, NETWORK, RESULT-QUEUE, LT),
        INVOKED ; (REACTORID . N), CONST && CONST', LT, PT, N2
      )
    if presetOK(PRE, GRAPH)   
    /\ allTriggersDecided(TSTATUS)  
    /\ result(OBJECT, OUTPUTS, RESULT-QUEUE, CONST') := 
         executeReaction(< REACTORID : Reactor | reactions : REACTIONS1
                                                 (reaction N when TRIGGERIDS --> OS do {RB} deadline TI {RB2} exTime T1 TI1)
                                                 REACTIONS2 >, N, TSTATUS, QUEUE, LT, PT) .

--- Execution finished. We update the APG execution status accordingly and we free one processor.
crl [finishExecuteReaction] :
  executeStep(
            < (REACTORID . N) : APGNode | status : executing(T) > 
            GRAPH,
            NETWORK
            < REACTORID : Reactor | 
                reactions : REACTIONS1 (reaction N when TRIGGERIDS --> OS do {RB} deadline TI {RB2} exTime T1 TI1 ) REACTIONS2 >,
            QUEUE,
            INVOKED, CONST, LT, PT, N2  --- last argument is the number of idle processors
            )
  =>
  executeStep(
            < (REACTORID . N) : APGNode | status : executed > 
            GRAPH,
            NETWORK
            < REACTORID : Reactor | >,
            QUEUE,
            INVOKED, CONST, LT, PT, s N2  --- last argument is the number of idle processors
            )
  if T ge T1 /\ T le TI1 .

  eq executeStep(
            GRAPH,
            NETWORK,
            QUEUE,
            INVOKED, CONST, LT, PT, N2
        )
  =
       NETWORK
       < Q : EventQueue | queue : QUEUE >
       < RXNS : Invoked | reactions : INVOKED >
       [physicalTime: PT]
       [numberProcessors: N2]
       if allFinished(GRAPH) .

---(
  ceq executeStep(
        < (REACTORID . N) : APGNode | 
            triggers : TSTATUS, status : present, pre : PRE, execStatus : executing(0) > 
        GRAPH,
        NETWORK
        < REACTORID : Reactor | 
            reactions : REACTIONS1 (reaction N when TRIGGERIDS --> OS do {RB} exTime T1 TI ) REACTIONS2 >,
        QUEUE,
        INVOKED, CONST, LT)
   =
      executeStep(
        < (REACTORID . N) : APGNode | status : executed >
        updateGraph(GRAPH, REACTORID, OS, NETWORK < REACTORID : Reactor | >, OUTPUTS),
        propagateImmediateOutputs(OUTPUTS, NETWORK OBJECT),    --- updated reactor
        scheduleDelayedInputs(OUTPUTS, NETWORK, RESULT-QUEUE, LT),
        INVOKED ; (REACTORID . N), CONST && CONST', LT)
   if presetOK(PRE, GRAPH)   
   /\ allTriggersDecided(TSTATUS)  
   /\ result(OBJECT, OUTPUTS, RESULT-QUEUE, CONST') := 
         executeReaction(< REACTORID : Reactor | reactions : REACTIONS1
                                                 (reaction N when TRIGGERIDS --> OS do {RB} exTime T1 TI)
                                                 REACTIONS2 >, N, TSTATUS, QUEUE, LT, PT) .

 *** Comment out for debugging with APG graph:
 ceq executeStep(GRAPH, NETWORK, QUEUE, INVOKED, CONST, LT, PT) 
   = networkQueueRxns(NETWORK, QUEUE, INVOKED, CONST) 
  if CONST == trueVal [owise] . --- for the concrete case, CONST must be true
)---

 --- non-owise version
---(
 ceq executeStep(GRAPH, NETWORK, QUEUE, INVOKED, CONST) 
   = networkQueueRxns(NETWORK, QUEUE, INVOKED, CONST) 
  if noMoreReaction(GRAPH, none)
  /\ CONST == trueVal . --- for the concrete case, CONST must be true
)---
endom
