in dynamics.maude

in TrainDoor_v3.maude

omod TEST-TRAIN is
  including TRAINDOOR-V3 .
  including DYNAMICS .

  ops env queue : -> Oid [ctor] .

  op initSystem : -> GlobalSystem .
  eq initSystem =
     { < env : Environment |
           physicalActions : < (controller . external) : PhysAct |
	                           leftOfPeriod : 0,
				   period : 10,
				   possibleValues : ([true]) >
                             < (door . extOpen) : PhysAct |
	                           leftOfPeriod : 0,
				   period : 2,
				   possibleValues : ([false]) > 
>
       init
       < queue : EventQueue | queue : empty >} .
                              
     
endom


rew [33] initSystem .

