in dynamics.maude

in TrainDoor_v2.maude

omod TEST-TRAIN is
  including TRAINDOOR-V2 .
  including DYNAMICS .

  ops env queue : -> Oid [ctor] .

  op initSystem : -> GlobalSystem .
  eq initSystem =
     { < env : Environment |
           physicalActions : < (controller . external) : PhysAct |
	                           leftOfPeriod : 0,
				   period : 50,
				   possibleValues : ([true]) > >
       init
       < queue : EventQueue | queue : empty >} .
                              
     
endom


rew [33] initSystem .

