in ADAS-with-camera.maude




omod TEST-ADAS is
  including ADAS-WITH-CAMERA .
  including DYNAMICS-WITHOUT-TICK .

  ops env queue : -> Oid [ctor] .

  op initSystem : -> GlobalSystem .
  eq initSystem =
     { < env : Environment |
           physicalActions : < (pedal . a) : PhysAct |
                                   leftOfPeriod : 5,
                                   period : 5,
                                   possibleValues : [69] : [71],
				   timeNonDet : true > >
       addReactionIndices(init)
       < queue : EventQueue | queue : addInitialTimers(init, empty) >} .
endom

rew [51] initSystem .


omod TIME-BOUNDED-ADAS is
  including TEST-ADAS .
  including TIME-BOUNDED-DYNAMICS  .
  eq timeBound = 55 .
endom  

*** Some new stuff for the paper:

--- 1. Time-bounded simulation:

rew initSystem in time 0 .


--- Also a time-bounded search, for brakes applied:
search [1] initSystem in time 0  =>*
    {REST:Configuration  < brakes : Reactor | state : (brakesApplied |-> [1]) ; RS:ReactorState,
                                         ATTS:AttributeSet >} in time T:Time .


omod MODEL-CHECK-ADAS is
  including MODEL-CHECKER .
  including TIME-BOUNDED-ADAS .
  including LF-PROP .
endom


red modelCheck(initSystem in time 0,
               <> (brakesApplied in brakes == [1])) .

--- exactly what Edward Lee wanted

--- We have directly modified the ADAS-without-camera file
---   by inserting the differenmt errors exemplified on page 19,
--- and in neither case does the formula hold

--- everything works here as well in the new setting, and with camera.

